language: python

env:
  global:
    - IMAGE_VERSION=2.1.0
    - CONTENTBOX_VERSION=3.7.0
  matrix:
    - BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Lucee4 BUILD_IMAGE_TAG=ortussolutions/contentbox:lucee45
    - BUILD_IMAGE_DOCKERFILE=engines/Dockerfile.Adobe2016 BUILD_IMAGE_TAG=ortussolutions/contentbox:adobe2016

services:
  - docker

script:
  - echo "Preparing to deploy!"

deploy:
  skip_cleanup: true
  on:
    branch: 
      - master
      - development
  provider: script
  script: ./resources/publish.sh
