language: python

env:
  global:
    - IMAGE_VERSION=5.0.0
    - CONTENTBOX_VERSION=4.2.1
  matrix:
    # Ubuntu Based
    - BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox
    # Alpine Based
    - BUILD_IMAGE_DOCKERFILE=engines/Alpine.Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox:alpine
    # Specific Servers
    - BUILD_IMAGE_DOCKERFILE=engines/Lucee5.Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox:lucee5
    - BUILD_IMAGE_DOCKERFILE=engines/Adobe2016.Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox:adobe2016
    - BUILD_IMAGE_DOCKERFILE=engines/Adobe2018.Dockerfile BUILD_IMAGE_TAG=ortussolutions/contentbox:adobe2018

services:
  - docker

script:
  - echo "Preparing to deploy!"

deploy:
  skip_cleanup: true
  on:
    branch: 
      - master
      - development
  provider: script
  script: ./resources/build.sh
